name: PR build check

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'oracle'

      - run: ./gradlew lint --stacktrace
